/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mastermind_console_fourcade_legier;

/**
 *
 * @author Legier
 */
public class fenetreMastermind extends javax.swing.JFrame {

    Grille grilleDeJeu = new Grille();
    Grille grilleOrdi = new Grille();
    Boule bouleCourant;

    public fenetreMastermind() {
        initComponents();

        for (int k = 0; k < 4; k++) {
            CelluleGraphique cellResultat = new CelluleGraphique(grilleOrdi.BouleJeu[1][k]);

            cellResultat.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Boule bouleOrdi = cellResultat.bouleAssociee;
                    grilleResultat.repaint();

                }
            });
            grilleResultat.add(cellResultat);
            grilleResultat.repaint();
        }

        for (int i = 9; i >= 0; i--) {
            for (int j = 0; j < 4; j++) {
                CelluleGraphique cellGraph = new CelluleGraphique(grilleDeJeu.BouleJeu[i][j]);

                cellGraph.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {

                        Boule b = cellGraph.bouleAssociee;
                        grille.repaint();

                        if (b.bouleCourant == null) {
                            return;
                        }

                    }
                });
                grille.add(cellGraph);
                grille.repaint();

            }
        }
    }

    /**
     * Creates new form fenetreMastermind
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grille = new javax.swing.JPanel();
        couleursDispo = new javax.swing.JPanel();
        boutoncouleur1 = new javax.swing.JButton();
        boutoncouleur2 = new javax.swing.JButton();
        boutoncouleur3 = new javax.swing.JButton();
        boutoncouleur4 = new javax.swing.JButton();
        boutoncouleur5 = new javax.swing.JButton();
        boutoncouleur6 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        grilleResultat = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grille.setBackground(new java.awt.Color(204, 204, 255));
        grille.setForeground(new java.awt.Color(153, 153, 255));
        grille.setLayout(new java.awt.GridLayout(11, 4));
        getContentPane().add(grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 490, 670));

        couleursDispo.setBackground(new java.awt.Color(153, 153, 153));
        couleursDispo.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout couleursDispoLayout = new javax.swing.GroupLayout(couleursDispo);
        couleursDispo.setLayout(couleursDispoLayout);
        couleursDispoLayout.setHorizontalGroup(
            couleursDispoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        couleursDispoLayout.setVerticalGroup(
            couleursDispoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        getContentPane().add(couleursDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 50, 340));

        boutoncouleur1.setText("jButton1");
        getContentPane().add(boutoncouleur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 690, 30, -1));

        boutoncouleur2.setText("1");
        getContentPane().add(boutoncouleur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 30, -1));

        boutoncouleur3.setText("1");
        getContentPane().add(boutoncouleur3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 30, 20));

        boutoncouleur4.setText("jButton1");
        getContentPane().add(boutoncouleur4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 510, 30, -1));

        boutoncouleur5.setText("jButton1");
        getContentPane().add(boutoncouleur5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 570, 30, -1));

        boutoncouleur6.setText("jButton1");
        getContentPane().add(boutoncouleur6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 630, 30, -1));

        jTextField1.setBackground(new java.awt.Color(51, 255, 255));
        jTextField1.setFont(new java.awt.Font("Arial", 3, 48)); // NOI18N
        jTextField1.setText("MASTERMIND");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Choisir un pion et le placer sur la grille :");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 260, 50));

        jTextField3.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jTextField3.setText("Résultat ordinateur :");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, -1, 30));

        grilleResultat.setBackground(new java.awt.Color(204, 204, 255));
        grilleResultat.setLayout(new java.awt.GridLayout(1, 4));
        getContentPane().add(grilleResultat, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 410, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetreMastermind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetreMastermind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetreMastermind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetreMastermind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetreMastermind().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutoncouleur1;
    private javax.swing.JButton boutoncouleur2;
    private javax.swing.JButton boutoncouleur3;
    private javax.swing.JButton boutoncouleur4;
    private javax.swing.JButton boutoncouleur5;
    private javax.swing.JButton boutoncouleur6;
    private javax.swing.JPanel couleursDispo;
    private javax.swing.JPanel grille;
    private javax.swing.JPanel grilleResultat;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
