/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mastermind_console_fourcade_legier;

/**
 *
 * @author Legier
 */
public class fenetreMastermind extends javax.swing.JFrame {

    Grille grilleDeJeu = new Grille();
    Boule bouleCourant ;

    public fenetreMastermind() {
        initComponents();

        for (int i = 9; i >= 0; i--) {
            for (int j = 0; j < 4; j++) {
                CelluleGraphique cellGraph = new CelluleGraphique(grilleDeJeu.BouleJeu[i][j]);

                cellGraph.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {

                        Boule b = cellGraph.bouleAssociee;
                        grille.repaint();
                        
                        if (b.bouleCourant == null) return;


                    }
                });
            grille.add(cellGraph);
            grille.repaint();
           
            }
        }
    }

    /**
     * Creates new form fenetreMastermind
     */
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grille = new javax.swing.JPanel();
        couleur1 = new javax.swing.JPanel();
        couleur2 = new javax.swing.JPanel();
        couleur3 = new javax.swing.JPanel();
        couleur4 = new javax.swing.JPanel();
        couleur5 = new javax.swing.JPanel();
        couleur6 = new javax.swing.JPanel();
        boutoncouleur1 = new javax.swing.JButton();
        boutoncouleur2 = new javax.swing.JButton();
        boutoncouleur3 = new javax.swing.JButton();
        boutoncouleur4 = new javax.swing.JButton();
        boutoncouleur5 = new javax.swing.JButton();
        boutoncouleur6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grille.setBackground(new java.awt.Color(204, 204, 255));
        grille.setForeground(new java.awt.Color(153, 153, 255));
        grille.setLayout(new java.awt.GridLayout(11, 4));
        getContentPane().add(grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 490, 670));

        couleur1.setBackground(new java.awt.Color(153, 153, 153));
        couleur1.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout couleur1Layout = new javax.swing.GroupLayout(couleur1);
        couleur1.setLayout(couleur1Layout);
        couleur1Layout.setHorizontalGroup(
            couleur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        couleur1Layout.setVerticalGroup(
            couleur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(couleur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, 50, 50));

        couleur2.setBackground(new java.awt.Color(153, 153, 153));
        couleur2.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout couleur2Layout = new javax.swing.GroupLayout(couleur2);
        couleur2.setLayout(couleur2Layout);
        couleur2Layout.setHorizontalGroup(
            couleur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        couleur2Layout.setVerticalGroup(
            couleur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(couleur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 680, 50, 50));

        couleur3.setBackground(new java.awt.Color(153, 153, 153));
        couleur3.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout couleur3Layout = new javax.swing.GroupLayout(couleur3);
        couleur3.setLayout(couleur3Layout);
        couleur3Layout.setHorizontalGroup(
            couleur3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        couleur3Layout.setVerticalGroup(
            couleur3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(couleur3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, 50, 50));

        couleur4.setBackground(new java.awt.Color(153, 153, 153));
        couleur4.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout couleur4Layout = new javax.swing.GroupLayout(couleur4);
        couleur4.setLayout(couleur4Layout);
        couleur4Layout.setHorizontalGroup(
            couleur4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        couleur4Layout.setVerticalGroup(
            couleur4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(couleur4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, -1, -1));

        couleur5.setBackground(new java.awt.Color(153, 153, 153));
        couleur5.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout couleur5Layout = new javax.swing.GroupLayout(couleur5);
        couleur5.setLayout(couleur5Layout);
        couleur5Layout.setHorizontalGroup(
            couleur5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        couleur5Layout.setVerticalGroup(
            couleur5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(couleur5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, -1, -1));

        couleur6.setBackground(new java.awt.Color(153, 153, 153));
        couleur6.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout couleur6Layout = new javax.swing.GroupLayout(couleur6);
        couleur6.setLayout(couleur6Layout);
        couleur6Layout.setHorizontalGroup(
            couleur6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        couleur6Layout.setVerticalGroup(
            couleur6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(couleur6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, -1, -1));

        boutoncouleur1.setText("jButton1");
        getContentPane().add(boutoncouleur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 690, 30, -1));

        boutoncouleur2.setText("1");
        getContentPane().add(boutoncouleur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 30, -1));

        boutoncouleur3.setText("1");
        getContentPane().add(boutoncouleur3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 30, 20));

        boutoncouleur4.setText("jButton1");
        getContentPane().add(boutoncouleur4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 510, 30, -1));

        boutoncouleur5.setText("jButton1");
        getContentPane().add(boutoncouleur5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 570, 30, -1));

        boutoncouleur6.setText("jButton1");
        getContentPane().add(boutoncouleur6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 630, 30, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetreMastermind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetreMastermind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetreMastermind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetreMastermind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetreMastermind().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutoncouleur1;
    private javax.swing.JButton boutoncouleur2;
    private javax.swing.JButton boutoncouleur3;
    private javax.swing.JButton boutoncouleur4;
    private javax.swing.JButton boutoncouleur5;
    private javax.swing.JButton boutoncouleur6;
    private javax.swing.JPanel couleur1;
    private javax.swing.JPanel couleur2;
    private javax.swing.JPanel couleur3;
    private javax.swing.JPanel couleur4;
    private javax.swing.JPanel couleur5;
    private javax.swing.JPanel couleur6;
    private javax.swing.JPanel grille;
    // End of variables declaration//GEN-END:variables
}
